# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [12]:
# Load the Food choices data set.
food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [15]:
print(df_food.shape)

(125, 61)

In [16]:
# Count by hand. (lol kidding)
print(df_food.shape)

(125, 61)

In [17]:
# Try to print or display it nicely.
display(df_food.head(5))

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [19]:
# Show the column names and their types.
print(df_food.dtypes)

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

In [20]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
column_info = pd.DataFrame({
    "data type": df_food.dtypes,
    "Non-null count": df_food.notnull().sum(),
    "Null count": df_food.isnull().sum()
    
})

display(column_info)

                             data type  Non-null count  Null count
GPA                             object             123           2
Gender                           int64             125           0
breakfast                        int64             125           0
calories_chicken                 int64             125           0
calories_day                   float64             106          19
calories_scone                 float64             124           1
coffee                           int64             125           0
comfort_food                    object             124           1
comfort_food_reasons            object             123           2
comfort_food_reasons_coded     float64             106          19
cook                           float64             122           3
comfort_food_reasons_coded.1     int64             125           0
cuisine                        float64             108          17
diet_current                    object             124           1
diet_current_coded               int64             125           0
drink                          float64             123           2
eating_changes                  object             122           3
eating_changes_coded             int64             125           0
eating_changes_coded1            int64             125           0
eating_out                       int64             125           0
employment                     float64             116           9
ethnic_food                      int64             125           0
exercise                       float64             112          13
father_education               float64             124           1
father_profession               object             122           3
fav_cuisine                     object             123           2
fav_cuisine_coded                int64             125           0
fav_food                       float64             123           2
food_childhood                  object             124           1
fries                            int64             125           0
fruit_day                        int64             125           0
grade_level                      int64             125           0
greek_food                       int64             125           0
healthy_feeling                  int64             125           0
healthy_meal                    object             124           1
ideal_diet                      object             124           1
ideal_diet_coded                 int64             125           0
income                         float64             124           1
indian_food                      int64             125           0
italian_food                     int64             125           0
life_rewarding                 float64             124           1
marital_status                 float64             124           1
meals_dinner_friend             object             122           3
mother_education               float64             122           3
mother_profession               object             123           2
nutritional_check                int64             125           0
on_off_campus                  float64             124           1
parents_cook                     int64             125           0
pay_meal_out                     int64             125           0
persian_food                   float64             124           1
self_perception_weight         float64             124           1
soup                           float64             124           1
sports                         float64             123           2
thai_food                        int64             125           0
tortilla_calories              float64             124           1
turkey_calories                  int64             125           0
type_sports                     object              99          26
veggies_day                      int64             125           0
vitamins                         int64             125           0
waffle_calories                  int64             125           0
weight                          object             123           2

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [21]:
# Remove ‘em.
df_food_col_subset = df_food[["calories_day", "weight", "Gender"]].copy()
df_food_col_subset.head(5)

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [22]:
# Is there a second way to remove columns?
df_food_col_subset = df_food.drop(columns=df_food.columns.difference(["calories_day", "weight", "Gender"]))
df_food_col_subset.head(5)

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [23]:
# Count ‘em.
df_food_col_subset.isna().sum()

Gender           0
calories_day    19
weight           2
dtype: int64

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [25]:
# Drop ‘em in-place.
df_food_col_subset = df_food_col_subset.dropna()
df_food_col_subset.isna().sum()

Gender          0
calories_day    0
weight          0
dtype: int64

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [26]:
# Fix that in-place.
df_food_col_subset = df_food_col_subset.dropna(inplace=False)
df_food_col_subset.head(5)

   Gender  calories_day                    weight
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190
5       1           3.0                       190

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [28]:
# Savey save!
df_food_col_subset.to_csv('../data/food_coded_cleaned.csv', index=False)

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [30]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [31]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [33]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)     object
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [34]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    "timestamp",
    "age",
    "industry",
    "title",
    "title_context",
    "salary",
    "additional_compensation",
    "currency",
    "other_currency",
    "salary_context",
    "country",
    "state",
    "city",
    "total_yoe",
    "field_yoe",
    "highest_education_completed",
    "gender",
    "race",
]
print(df_salary.dtypes)

timestamp                       object
age                             object
industry                        object
title                           object
title_context                   object
salary                          object
additional_compensation        float64
currency                        object
other_currency                  object
salary_context                  object
country                         object
state                           object
city                            object
total_yoe                       object
field_yoe                       object
highest_education_completed     object
gender                          object
race                            object
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [35]:
# List the unique industries and a count of their instances.
df_salary = df_salary[df_salary["industry"] == "Computing or Tech"].copy()
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [37]:
# Filtery filter.
df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"].copy()
df_salary_tech.head(5)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [38]:
# Sanity check count.
df_salary_tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [39]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech["currency"] == "USD"].copy()
df_salary_tech.head(5)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [40]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech["country"].value_counts(ascending=False).head(10)

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
United States                 68
Usa                           59
USA                           56
usa                           28
United states                 23
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [41]:
# Replace them all in-place with 'US'.
df_salary_tech["country"] = df_salary_tech["country"].replace(["United States", "USA", "United States of America", "U.S.", "Usa", "usa"], "US")

Have a look at the count of each unique country again now.

In [42]:
# Count again.
df_salary_tech["country"].value_counts(ascending=False).head(10)

country
US                           3495
United States                  68
USA                            56
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [43]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech["salary"] = pd.to_numeric(df_salary_tech["salary"], errors="coerce")
df_salary_tech.groupby("state")["salary"].agg(["min", "mean", "max"]).sort_values(by="mean", ascending=False)

                                     min           mean        max
state
Michigan, Texas, Washington     340000.0  340000.000000   340000.0
Florida                          28800.0  210711.000000  2600000.0
California, Oregon              200000.0  200000.000000   200000.0
California, Colorado            176000.0  176000.000000   176000.0
Delaware                        169000.0  169000.000000   169000.0
Connecticut                      68000.0  161610.000000   270000.0
California                           0.0  153286.988827   520000.0
New York                         14000.0  146594.112150   590000.0
Wisconsin                            1.0  145806.888889   920000.0
District of Columbia             59000.0  142923.076923   200000.0
New Jersey, New York            135000.0  137500.000000   140000.0
Ohio                             42000.0  137066.666667   954000.0
Washington                          72.0  136923.916667   300000.0
Massachusetts                    41000.0  125899.155844   400000.0
Nevada                          107100.0  124550.000000   142000.0
New Jersey                       67500.0  124090.909091   192000.0
Oregon                           16200.0  122640.000000   230000.0
West Virginia                   120000.0  120000.000000   120000.0
Maryland                         62000.0  119955.461538   176000.0
Illinois                         36000.0  117555.571429   228800.0
Alabama                          35000.0  117400.000000   350000.0
Louisiana, Washington           117000.0  117000.000000   117000.0
Pennsylvania                     52000.0  116826.388889   237000.0
Georgia                          29120.0  115297.647059   242000.0
Virginia                         58750.0  115086.696970   378000.0
Montana                          65000.0  112666.666667   145000.0
Kansas                           41500.0  109666.666667   167000.0
Colorado                         49400.0  109291.891892   165000.0
District of Columbia, Virginia  109200.0  109200.000000   109200.0
Vermont                          91250.0  105625.000000   120000.0
Idaho                            74860.0  105465.000000   170000.0
Utah                             33280.0  105023.333333   176000.0
Maine                            50000.0  103833.333333   173000.0
Texas                            10700.0  103685.245902   190000.0
Kentucky                         62000.0  102500.000000   125000.0
Iowa                             63000.0  101200.000000   142000.0
Minnesota                        52124.0  101064.941176   210000.0
Rhode Island                     76000.0   99475.000000   122950.0
North Carolina                   29000.0   97841.666667   165000.0
Arizona                          35000.0   97833.333333   145000.0
Michigan                         41600.0   95758.823529   235000.0
New Mexico                       82000.0   95733.333333   115200.0
Tennessee                        61500.0   91750.000000   144000.0
New Hampshire                       55.0   87175.833333   130000.0
Oklahoma                         36958.0   84802.571429   180000.0
Indiana                          15000.0   82875.000000   140000.0
California, Maryland             81500.0   81500.000000    81500.0
Louisiana                        75000.0   80500.000000    84000.0
Missouri                            80.0   80339.923077   200000.0
Nebraska                         43000.0   76736.000000   140000.0
Arkansas                             4.0   58001.000000    95000.0
South Carolina                   40000.0   40000.000000    40000.0
Alabama, District of Columbia        NaN            NaN        NaN
Alabama, Montana                     NaN            NaN        NaN
Alaska                               NaN            NaN        NaN
Arizona, Utah                        NaN            NaN        NaN
Georgia, Massachusetts               NaN            NaN        NaN
Georgia, Washington                  NaN            NaN        NaN
Massachusetts, New Hampshire         NaN            NaN        NaN
Massachusetts, Pennsylvania          NaN            NaN        NaN
Massachusetts, Rhode Island          NaN            NaN        NaN
Mississippi                          NaN            NaN        NaN
New York, Texas                      NaN            NaN        NaN
North Dakota                         NaN            NaN        NaN
South Dakota                         NaN            NaN        NaN
Utah, Vermont                        NaN            NaN        NaN

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [44]:
# Fix it in-place.
df_salary_tech["salary"] = pd.to_numeric(df_salary_tech["salary"], errors="coerce")

Let’s try that again.

In [45]:
# Try it again. Yeah!
df_salary_tech.groupby("state")["salary"].agg(["min", "mean", "max"]).sort_values(by="mean", ascending=False)

                                     min           mean        max
state
Michigan, Texas, Washington     340000.0  340000.000000   340000.0
Florida                          28800.0  210711.000000  2600000.0
California, Oregon              200000.0  200000.000000   200000.0
California, Colorado            176000.0  176000.000000   176000.0
Delaware                        169000.0  169000.000000   169000.0
Connecticut                      68000.0  161610.000000   270000.0
California                           0.0  153286.988827   520000.0
New York                         14000.0  146594.112150   590000.0
Wisconsin                            1.0  145806.888889   920000.0
District of Columbia             59000.0  142923.076923   200000.0
New Jersey, New York            135000.0  137500.000000   140000.0
Ohio                             42000.0  137066.666667   954000.0
Washington                          72.0  136923.916667   300000.0
Massachusetts                    41000.0  125899.155844   400000.0
Nevada                          107100.0  124550.000000   142000.0
New Jersey                       67500.0  124090.909091   192000.0
Oregon                           16200.0  122640.000000   230000.0
West Virginia                   120000.0  120000.000000   120000.0
Maryland                         62000.0  119955.461538   176000.0
Illinois                         36000.0  117555.571429   228800.0
Alabama                          35000.0  117400.000000   350000.0
Louisiana, Washington           117000.0  117000.000000   117000.0
Pennsylvania                     52000.0  116826.388889   237000.0
Georgia                          29120.0  115297.647059   242000.0
Virginia                         58750.0  115086.696970   378000.0
Montana                          65000.0  112666.666667   145000.0
Kansas                           41500.0  109666.666667   167000.0
Colorado                         49400.0  109291.891892   165000.0
District of Columbia, Virginia  109200.0  109200.000000   109200.0
Vermont                          91250.0  105625.000000   120000.0
Idaho                            74860.0  105465.000000   170000.0
Utah                             33280.0  105023.333333   176000.0
Maine                            50000.0  103833.333333   173000.0
Texas                            10700.0  103685.245902   190000.0
Kentucky                         62000.0  102500.000000   125000.0
Iowa                             63000.0  101200.000000   142000.0
Minnesota                        52124.0  101064.941176   210000.0
Rhode Island                     76000.0   99475.000000   122950.0
North Carolina                   29000.0   97841.666667   165000.0
Arizona                          35000.0   97833.333333   145000.0
Michigan                         41600.0   95758.823529   235000.0
New Mexico                       82000.0   95733.333333   115200.0
Tennessee                        61500.0   91750.000000   144000.0
New Hampshire                       55.0   87175.833333   130000.0
Oklahoma                         36958.0   84802.571429   180000.0
Indiana                          15000.0   82875.000000   140000.0
California, Maryland             81500.0   81500.000000    81500.0
Louisiana                        75000.0   80500.000000    84000.0
Missouri                            80.0   80339.923077   200000.0
Nebraska                         43000.0   76736.000000   140000.0
Arkansas                             4.0   58001.000000    95000.0
South Carolina                   40000.0   40000.000000    40000.0
Alabama, District of Columbia        NaN            NaN        NaN
Alabama, Montana                     NaN            NaN        NaN
Alaska                               NaN            NaN        NaN
Arizona, Utah                        NaN            NaN        NaN
Georgia, Massachusetts               NaN            NaN        NaN
Georgia, Washington                  NaN            NaN        NaN
Massachusetts, New Hampshire         NaN            NaN        NaN
Massachusetts, Pennsylvania          NaN            NaN        NaN
Massachusetts, Rhode Island          NaN            NaN        NaN
Mississippi                          NaN            NaN        NaN
New York, Texas                      NaN            NaN        NaN
North Dakota                         NaN            NaN        NaN
South Dakota                         NaN            NaN        NaN
Utah, Vermont                        NaN            NaN        NaN

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [46]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"], errors="coerce")
df_salary_tech_21_22 = df_salary_tech[df_salary_tech["timestamp"].dt.year.isin([2021, 2022, 2023])].copy() 
df_salary_tech_21_22["timestamp"].dt.year.value_counts()

timestamp
2021    3710
2022      40
2023      14
Name: count, dtype: int64

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)